name: HESI Build Windows 64-bit RustDesk

on:
  workflow_dispatch:  # 允许手动触发工作流
  push:
    branches:
      - master  # 分支名称设置为 master

jobs:
  run-windows-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: "windows-64bit"
