name: HESI Build Windows Version

on:
  workflow_dispatch:
    inputs:
      upload-artifact:
        description: 'Upload artifacts to GitHub'
        required: true
        default: 'true'
        type: boolean
      upload-tag:
        description: 'Tag name for the release'
        required: true
        default: 'nightly'
        type: string

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.4.0"
  NDK_VERSION: "r27c"
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  TAG_NAME: "${{ inputs.upload-tag }}"

jobs:
  build-for-windows-flutter:
    name: Build Windows Flutter Version
    runs-on: windows-2022
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Build RustDesk
        run: |
          # Windows: build RustDesk
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          if (-Not (Test-Path -Path "./flutter/build/windows/x64/runner/Release")) {
            Write-Error "Path './flutter/build/windows/x64/runner/Release' does not exist."
            exit 1
          }
          Move-Item -Path ./flutter/build/windows/x64/runner/Release -Destination ./rustdesk -Force

      - name: Upload Artifacts
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: actions/upload-artifact@master
        with:
          name: rustdesk-windows-${{ matrix.job.arch }}
          path: rustdesk

      - name: Publish Release
        if: env.UPLOAD_ARTIFACT == 'true'
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: ${{ env.TAG_NAME }}
          files: |
            rustdesk-*.msi
            rustdesk-*.exe
